modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
[[mods]]
modId = "laboratoryblocks"
version = "${file.jarVersion}"
displayName = "Artemis' Laboratory Blocks"
authors="Artemis"
description = '''
This mod adds futuristic and clean looking laboratory blocks
'''
[[dependencies.laboratoryblocks]]
    modId = "forge"
    mandatory = true
    versionRange = "[40,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.laboratoryblocks]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18,1.19)"
    ordering = "NONE"
    side = "BOTH"
