modLoader = "javafml"
loaderVersion = "[43,)"
license = "All Rights Reserved"
[[mods]]
modId = "laboratoryblocks"
version = "${file.jarVersion}"
displayName = "LaboratoryBlocks"
authors="Artemis"
description = '''
This mod adds futuristic and clean laboratory blocks
'''
[[dependencies.laboratoryblocks]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.laboratoryblocks]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
