modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-2.0"
[[mods]]
modId = "laboratoryblocks"
version = "${file.jarVersion}"
displayName = "Artemis' Laboratory Blocks"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/artemis-laboratory-blocks"
logoFile = "artemis_laboratory_blocks-logo.png"
logoBlur = true
authors="Artemis"
description = '''
Get ready to upgrade your builds! This mod adds modern and futuristic looking laboratory blocks. Plus, it's compatible with CTM (ConnectedTexturesMod) and Fusion for even better visuals.
'''

[[dependencies.laboratoryblocks]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.0,21.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.laboratoryblocks]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21,1.21.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.laboratoryblocks]]
    modId = "fusion"
    type = "required"
    versionRange = "[1.0.3,)"
    ordering = "NONE"
    side = "CLIENT"
